[package]
name = "bdays"
version = "0.1.0"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]

[dependencies]
chrono = "0.4.6"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false